#!/usr/bin/env bash
# One-shot Authelia setup: hash password, build users_database.yml, deploy to NAS.
# Hash: tries local 'authelia' CLI (e.g. brew install authelia) then Docker.
# Requires: authelia in PATH or Docker; SSH + truenas-sudo for deploy.
#
# Usage:
#   ./scripts/truenas/authelia-setup-with-docker.sh
#   ./scripts/truenas/authelia-setup-with-docker.sh my_username

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
USERS_FILE=""
DBG() { echo "[authelia-setup] $*"; }

DBG "start: SCRIPT_DIR=$SCRIPT_DIR DOTFILES_ROOT=$DOTFILES_ROOT"

# Ensure Docker daemon is reachable (e.g. Cursor/IDE may not inherit DOCKER_HOST on macOS)
ensure_docker() {
  DBG "ensure_docker: checking for docker..."
  if ! command -v docker &>/dev/null; then
    DBG "ensure_docker: docker not in PATH"; return 1
  fi
  DBG "ensure_docker: docker at $(command -v docker)"
  if docker info &>/dev/null; then
    DBG "ensure_docker: docker info OK (DOCKER_HOST=${DOCKER_HOST:-<unset>})"; return 0
  fi
  DBG "ensure_docker: docker info failed, trying macOS socket..."
  [[ "$(uname -s)" != "Darwin" ]] && { DBG "ensure_docker: not Darwin, giving up"; return 1; }
  for sock in "$HOME/.docker/run/docker.sock" "/var/run/docker.sock"; do
    if [[ -S "$sock" ]]; then
      export DOCKER_HOST="unix://$sock"
      DBG "ensure_docker: trying DOCKER_HOST=$DOCKER_HOST"
      if docker info &>/dev/null; then
        DBG "ensure_docker: docker info OK with $DOCKER_HOST"; return 0
      fi
    fi
  done
  DBG "ensure_docker: could not reach daemon"; return 1
}

cleanup() { [[ -n "$USERS_FILE" && -f "$USERS_FILE" ]] && rm -f "$USERS_FILE"; }
trap cleanup EXIT

USERNAME="${1:-}"
if [[ -z "$USERNAME" ]]; then
  read -rp "Authelia username: " USERNAME
  if [[ -z "$USERNAME" ]]; then
    echo "Error: username required." >&2
    exit 1
  fi
fi

echo "Password for $USERNAME (input hidden):"
read -rs PASSWORD
echo
if [[ -z "$PASSWORD" ]]; then
  echo "Error: no password entered." >&2
  exit 1
fi

read -rp "Email for $USERNAME (optional, for password reset): " EMAIL

# Generate Argon2 hash: try local authelia first, then Docker
is_hash() { [[ "${1:-}" =~ ^\$argon2 ]]; }
HASH=""

if command -v authelia &>/dev/null; then
  echo "Generating Argon2 hash (authelia CLI)..."
  HASH=$(authelia crypto hash generate argon2 --password "$PASSWORD" 2>/dev/null) || true
  is_hash "$HASH" || HASH=""
  DBG "hash via authelia CLI: is_hash=$([[ -n "$HASH" ]] && echo yes || echo no)"
fi

if [[ -z "$HASH" ]] && ensure_docker; then
  echo "Generating Argon2 hash via Docker..."
  DOCKER_OUT=$(docker run --rm authelia/authelia:latest authelia crypto hash generate argon2 --password "$PASSWORD" 2>&1) || true
  DBG "docker run exit code: $?"
  HASH=$(echo "$DOCKER_OUT" | grep -o '\$argon2[^[:space:]]*' | head -1)
  DBG "hash via Docker: is_hash=$([[ -n "$HASH" ]] && echo yes || echo no), raw_output_lines=$(echo "$DOCKER_OUT" | wc -l)"
fi

unset PASSWORD

if [[ -z "$HASH" ]]; then
  echo "Error: failed to generate hash." >&2
  echo "Authelia does not publish macOS binaries; use Docker." >&2
  echo "Start Docker Desktop and re-run this script." >&2
  exit 1
fi
DBG "hash length=${#HASH} prefix=${HASH:0:30}..."

USERS_FILE=$(mktemp)
DBG "USERS_FILE=$USERS_FILE"
cat > "$USERS_FILE" << EOF
# Generated by authelia-setup-with-docker.sh

users:
  $USERNAME:
    displayname: "$USERNAME"
    password: "$HASH"
$( [[ -n "$EMAIL" ]] && echo "    email: \"$EMAIL\"" )
    groups: []
EOF
DBG "wrote users_database content to $USERS_FILE ($(wc -l < "$USERS_FILE") lines)"

echo "Deploying configuration.yml and users_database.yml to NAS..."
export USERS_FILE
DBG "calling authelia-deploy-config.sh (USERS_FILE=$USERS_FILE)"
"$SCRIPT_DIR/authelia-deploy-config.sh"
DEPLOY_EXIT=$?
DBG "authelia-deploy-config.sh exited with code $DEPLOY_EXIT"
[[ $DEPLOY_EXIT -ne 0 ]] && exit $DEPLOY_EXIT

echo ""
echo "All set. Restart Authelia: TrueNAS → Apps → authelia → Stop → Start"
DBG "done."
