#!/usr/bin/env python3
"""Ugoos SK1 system inventory via ADB. Rich dashboard, detailed output to file.

Requires: adb in PATH, SK1 connected (adb connect 192.168.0.159:5555).

Usage:
  python sk1-inventory-rich.py [output_path]
  python sk1-inventory-rich.py
  python sk1-inventory-rich.py ~/dotfiles/docs/hardware/ugoos-sk1-inventory.txt
"""

import subprocess
import sys
from pathlib import Path

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn
    from rich.table import Table
    from rich.theme import Theme
    RICH_AVAILABLE = True
except ImportError:
    try:
        subprocess.run([sys.executable, "-m", "pip", "install", "rich", "-q"], check=True, capture_output=True)
        from rich.console import Console
        from rich.panel import Panel
        from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn
        from rich.table import Table
        from rich.theme import Theme
        RICH_AVAILABLE = True
    except Exception:
        RICH_AVAILABLE = False

THEME = Theme({
    "primary": "bold cyan",
    "success": "green",
    "danger": "bold red",
    "warning": "yellow",
    "muted": "dim white",
})

DEFAULT_DEVICE = "192.168.0.159:5555"
DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent.parent / "docs" / "hardware" / "ugoos-sk1-inventory.txt"


def adb_shell(device: str, cmd: str) -> tuple[str, int]:
    full = ["adb", "-s", device, "shell", cmd]
    result = subprocess.run(full, capture_output=True, text=True, timeout=60)
    return (result.stdout or "") + (result.stderr or ""), result.returncode


def gather_inventory(device: str) -> tuple[str, dict]:
    sections: list[str] = []
    summary: dict[str, str] = {}

    def section(title: str, content: str):
        sections.append(f"\n## {title}\n\n{content}")
        return content

    out, rc = adb_shell(device, "getprop")
    if rc != 0:
        return "\n".join(sections) if sections else "ADB connection failed", summary

    props = {}
    for line in out.splitlines():
        if "]:" in line:
            try:
                k, v = line.strip().replace("[", "").split("]: ", 1)
                v = v.rstrip("]")
                props[k] = v
            except ValueError:
                pass

    summary["model"] = props.get("ro.product.model", "?")
    summary["serial"] = props.get("ro.serialno", "?")
    summary["build"] = props.get("ro.build.display.id", "?")
    summary["android"] = props.get("ro.build.version.release", "?")
    summary["sdk"] = props.get("ro.build.version.sdk", "?")
    summary["abi"] = props.get("ro.product.cpu.abi", "?")
    summary["build_date"] = props.get("ro.build.date", "?")

    section("Identity", "\n".join(f"{k}: {v}" for k, v in [
        ("Model", summary["model"]),
        ("Serial", summary["serial"]),
        ("Build", summary["build"]),
        ("Android", summary["android"]),
        ("SDK", summary["sdk"]),
        ("ABI", summary["abi"]),
        ("Build Date", summary["build_date"]),
    ]))

    out, _ = adb_shell(device, "cat /proc/cpuinfo")
    section("CPU", out[:2000] + ("\n...(truncated)" if len(out) > 2000 else ""))

    out, _ = adb_shell(device, "cat /proc/meminfo")
    section("Memory", out)

    out, _ = adb_shell(device, "df -h")
    section("Storage", out)

    out, _ = adb_shell(device, "ip addr")
    section("Network", out)

    out, _ = adb_shell(device, "dumpsys wifi")
    section("WiFi", out[:3000] + ("\n...(truncated)" if len(out) > 3000 else ""))

    out, _ = adb_shell(device, "dumpsys diskstats")
    section("Disk Stats", out)

    out, _ = adb_shell(device, "getprop")
    section("All Build Properties", out)

    out, _ = adb_shell(device, "pm list packages -3")
    section("User-Installed Packages", out)

    header = (
        f"# Ugoos SK1 System Inventory\n"
        f"Device: {device}\n"
        f"Generated by sk1-inventory-rich.py\n"
    )
    full_output = header + "\n".join(sections) + "\n\n---\n*End of inventory*"
    return full_output, summary


def main() -> int:
    device = "192.168.0.159:5555"
    output_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUTPUT
    output_path = output_path.expanduser().resolve()

    if not RICH_AVAILABLE:
        print("Error: rich not available", file=sys.stderr)
        return 1

    console = Console(theme=THEME, force_terminal=True)

    console.print(Panel(
        f"[primary]Device:[/] {device}\n"
        f"[primary]Output:[/] {output_path}\n"
        f"[muted]Connecting and gathering...[/]",
        title="[primary]SK1 System Inventory[/]",
        border_style="cyan",
    ))

    full_output = ""
    summary: dict[str, str] = {}
    steps = ["Identity", "CPU", "Memory", "Storage", "Network", "WiFi", "Disk", "Props", "Packages"]

    with Progress(
        SpinnerColumn(),
        TextColumn("[primary]{task.description}[/]"),
        BarColumn(bar_width=40, style="dim", complete_style="cyan"),
        TaskProgressColumn(),
        console=console,
    ) as progress:
        task = progress.add_task("Gathering...", total=len(steps))
        full_output, summary = gather_inventory(device)
        progress.update(task, description="Complete", completed=len(steps))

    if not full_output or "ADB connection failed" in full_output:
        console.print("[danger]ADB connection failed. Ensure: adb connect 192.168.0.159:5555[/]")
        return 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(full_output, encoding="utf-8")

    table = Table(title="[success]Summary[/]")
    table.add_column("Field", style="cyan")
    table.add_column("Value", style="white")
    for k, v in summary.items():
        table.add_row(k, str(v)[:60])

    console.print()
    console.print(table)
    console.print()
    console.print(Panel(
        f"[success]Saved to[/] {output_path}\n"
        f"[muted]Lines:[/] {len(full_output.splitlines())}",
        title="[success]Done[/]",
        border_style="green",
    ))
    return 0


if __name__ == "__main__":
    sys.exit(main())
