"""
Configuration file for Factorio NPC Controller
Edit these values to match your setup.
"""

# Factorio RCON Configuration
RCON_HOST = "192.168.0.158"  # NAS IP address
RCON_PORT = 27015
RCON_PASSWORD = "Sahb5aevu3neiph"  # RCON password from server logs (generated by container)

# Ollama Configuration
# Recommended models for NPCs (fast decision-making):
# - "phi3:mini" (3.8B) - FASTEST, smallest, best for quick decisions
# - "mistral" (7B) - Fast and efficient, good for NPCs, reliable JSON
# - "qwen2.5:7b" (7B) - Good reasoning, balanced
# - "llama3.1" (8B) - Better decisions but slower
OLLAMA_MODEL = "phi3:mini"  # Fastest model (3.8B) for quick NPC decisions
OLLAMA_HOST = "localhost"  # Ollama runs on local Mac; when controller on NAS set OLLAMA_HOST to Mac IP (or use env)
OLLAMA_PORT = 11434

# NPC Configuration
DEFAULT_DECISION_INTERVAL = 5.0  # Seconds between decision cycles
MAX_CONTEXT_HISTORY = 10  # Number of messages to keep in conversation history

# Base Range Limits (used only by factorio_ollama_npc_controller; HTTP controller does not enforce)
# Set high to effectively disable movement restrictions for now.
MAX_RANGE_FROM_BASE = 999999  # 200 = strict; 999999 = no restriction from our code

# Logging
LOG_LEVEL = "INFO"  # DEBUG, INFO, WARNING, ERROR
